/*
 *
 * Copyright 2016 gRPC authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
/* This file is autogenerated from:
   templates/src/core/surface/version.c.template */

#include <grpcpp/grpcpp.h>

namespace grpc {
grpc::string Version() < < < < < < < HEAD { return "1.27.0-dev"; }
|||||||
{ return "1.26.0-dev"; }
=======
{ return "1.26.0"; }
>>>>>>> 78ace4cd5dfcc1f2eced44d22d752f103f377e7b

}  // namespace grpc